Trace file /u01/app/oracle/diag/rdbms/orcl19/orcl19/trace/orcl19_fenc_28322.trc
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
Build label:    RDBMS_19.3.0.0.0DBRU_LINUX.X64_190417
ORACLE_HOME:    /u01/app/oracle/product/19c/dbhome_1
System name:	Linux
Node name:	bastionlogan
Release:	5.4.17-2036.103.3.1.el7uek.x86_64
Version:	#2 SMP Sun Feb 14 12:48:17 PST 2021
Machine:	x86_64
Instance name: orcl19
Redo thread mounted by this instance: 0 <none>
Oracle process number: 31
Unix process pid: 28322, image: oracle@bastionlogan (FENC)


*** 2021-03-11T06:18:24.555433+00:00 (CDB$ROOT(1))
*** SESSION ID:(254.45291) 2021-03-11T06:18:24.555463+00:00
*** CLIENT ID:() 2021-03-11T06:18:24.555468+00:00
*** SERVICE NAME:() 2021-03-11T06:18:24.555472+00:00
*** MODULE NAME:() 2021-03-11T06:18:24.555475+00:00
*** ACTION NAME:() 2021-03-11T06:18:24.555479+00:00
*** CLIENT DRIVER:() 2021-03-11T06:18:24.555483+00:00
*** CONTAINER ID:(1) 2021-03-11T06:18:24.555488+00:00
 
2021-03-11 06:18:24.555 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18feeac0 [0000000000000014] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-11 06:18:24.555 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18feeac0 [000000000000001c] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
[ default][ default]u_set_comp_error: comptype '103' : error '29'
2021-03-11 06:18:24.557 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18ff7d80 [000000000000002d] { gipcAddress : name 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-11 06:18:24.557 : [GIPCXCPT][GIPCXCPT] gipcConnectSyncF [clscrsconGipcConnect : clscrscon.c : 686]: EXCEPTION[ ret gipcretConnectionRefused (29) ]  failed sync connect endp 0x18ff8260 [000000000000002a] { gipcEndpoint : localAddr 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=)(GIPCID=00000000-00000000-0))', remoteAddr 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', numPend 0, numReady 0, numDone 0, numDead 0, numTransfer 0, objFlags 0x0, pidPeer 0, readyRef (nil), ready 0, wobj 0x18fee8c0, sendp 0x18fedd50 status 13flags 0xa108071a, flags-2 0x0, usrFlags 0x0 }, addr 0x18ff7d80 [000000000000002d] { gipcAddress : name 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', objFlags 0x0, addrFlags 0x4 }, flags 0x0
2021-03-11 06:18:24.557 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18fedd50 [0000000000000032] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-11 06:18:24.557 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18fed480 [000000000000003a] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
[ default][ default]u_set_comp_error: comptype '103' : error '29'
2021-03-11 06:18:24.560 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18fed480 [000000000000004a] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-11 06:18:24.561 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x18fed480 [0000000000000052] { gipcAddress : name 'ipc://scls_opct_bastionlogan', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-11 06:18:24.561 : [  OCRRAW][  OCRRAW]proprioo: cannot get current configuration (33)
[ default][ default]u_set_gbl_comp_error: comptype '107' : error '2'
2021-03-11 06:18:24.561 : [  OCRRAW][  OCRRAW]proprinit: Could not open raw device 
2021-03-11 06:18:24.561 : [ default][ default]a_init:7!: Backend init unsuccessful : [33]
2021-03-11 06:18:24.561 : [ default][ default]clsutcnr:5.1: procr_init_ext failed [33] with bootlevel [131072]. Error data []. Return [5]
